### PR TITLE
HelloName solution

### PR DESCRIPTION
**Pull request by manasworks**
Test Pull Request

### CODE REVIEW

**Comment by manasworks** [comment]
Guys please take a look and if everything is fine give your approval to merge to master

**Review by aizadacoleman — APPROVED** [review]
Looks great!

**Comment by StanBek** [comment]
test

**Comment by Tahmina88** [comment]
looks good

**Review by Tahmina88 — COMMENTED** [review]
ok

**Comment by AsylUmar** [comment]
top notch

**Review by aakylbekova — APPROVED** [review]

**Review by StanBek — APPROVED** [review]

**Pull request merged**
