### PR TITLE
Update Test.java

### PR DESCRIPTION
**Pull request by elvirka7**
added space inside curly braces

### CODE REVIEW

**Comment by manasworks** [comment]
Nice job

**Review by manasworks — APPROVED** [review]

**Comment by aizadacoleman** [comment]
Looks good!

**Review by aizadacoleman — APPROVED** [review]

**Comment by Tahmina88** [comment]
cool

**Comment by AsylUmar** [comment]
Nice work

**Review by aakylbekova — APPROVED** [review]

**Pull request merged**
